### ISSUE TITLE
Show menu entry only if user is not authenticated

### ISSUE THREAD

**Issue by markus-fischbacher** [alterphp/EasyAdminExtensionBundle#100]
Hi there,

is there a way to show menu entries only if a user is not authenticated?
Using IS_AUTHENTICATED_ANONYMOUSLY is not possible, because that role every user has.
I want to show Register and Login only to not authenticated users.

Thanks!
Markus

**Comment by alterphp** [comment]
I don't know if you can ask Security AuthorizationChecker to return a dummy role when nobody is authenticated...

The whole security layer is being transferred to EasyAdmin bundle, and hopefully, will not be part of extension bundle in the next weeks ;-)
