### ISSUE TITLE
Override layout

### ISSUE THREAD

**Issue by Gu3** [alterphp/EasyAdminExtensionBundle#104]
Hi ! 
I used EasyAdminBundle (2.1) and I override the layout template thanks to my custom twig template inside template/bundles/EasyAdminBundle/default/layout.html.twig

But if I add EasyAdminExtensionBundle, the layout was not override anymore. 
I try to define my custom template inside template/bundles/EasyAdminExtensionBundle/default/layout.html.twig, without any luck. 

I allready look this issue : https://github.com/alterphp/EasyAdminExtensionBundle/issues/25, but I think this was before the new EasyAdminBundle. 

Thanks for your help !

**Comment by alterphp** [comment]
Hi @Gu3 !

Can I see the `design` part of your `easy_admin` configuration, and what your custom layout template is extending ?

**Comment by Gu3** [comment]
Hi ! 
Thanks for the quick anwser ! 
This is my design part : 

![image](https://user-images.githubusercontent.com/5227741/52998708-44d83d80-3424-11e9-99ce-7ae154287927.png)

And my custom layout extends nothing : I redesign it from scratch. But even if I override the list template (for example, with an empty file) I've got an empty page for the list view, and if I add easyAdminExtension, I've got the original list view. 

This is how I proceceed : https://symfony.com/doc/master/bundles/EasyAdminBundle/book/edit-new-configuration.html#overriding-the-default-templates-using-symfony-s-mechanism

But, maybe I need to do this : https://symfony.com/doc/master/bundles/EasyAdminBundle/book/edit-new-configuration.html#using-your-own-templates-to-display-the-list-search-show-views   ?

Cheers !

**Comment by alterphp** [comment]
Ok.

TwigPathPass override default symfony overriding.

NB: Symfony\Bundle\TwigBundle\DependencyInjection\TwigExtension::load => getBundleTemplatePaths is executed before the TwigPathPass...

**Comment by alterphp** [comment]
* First step : write a test that fails while checking that project overrides is "above" EasyAdminExtension twig paths. (`dump($this->get('twig')->getLoader()->getPaths('EasyAdmin'));`)
* Find the solution

**Comment by Gu3** [comment]
Ok, so this is my Namespaced twig paths for EasyAdmin : 

![image](https://user-images.githubusercontent.com/5227741/53048531-43932900-3495-11e9-9e40-c0f99568c74d.png)

if someone is interrested, this is my solution to override template : 
inside src/kernel.php at the end of configureContainer, add  : 
`$container->addCompilerPass(new TwigPathPass($this), PassConfig::TYPE_BEFORE_OPTIMIZATION);`

create src/DependencyInjection/Compiler/TwigPathPass.php

![image](https://user-images.githubusercontent.com/5227741/53048383-e4cdaf80-3494-11e9-8e71-c997b25c81fc.png)

Result is : 

![image](https://user-images.githubusercontent.com/5227741/53048584-63c2e800-3495-11e9-8be6-b8fdfcd2365f.png)

Thanks for the tips :) 
Cheers !

**Comment by alterphp** [comment]
Thank you @Gu3 for your solution.

I re-open the issue because it should be dealt in the bundle.

**Comment by alterphp** [comment]
I have opened an issue in symfony/symfony project to see if it should be handled on the framework level : https://github.com/symfony/symfony/issues/30359

**Comment by Gu3** [comment]
Nice ! 
Thanks !

**Comment by phcorp** [comment]
To override layout:

create file `src/DependencyInjection/Compiler/TwigPathPass.php`

```php
<?php

namespace App\DependencyInjection\Compiler;

use AlterPHP\EasyAdminExtensionBundle\EasyAdminExtensionBundle;
use App\AppBundle;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class TwigPathPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $twigLoaderFilesystemId = $container->getAlias('twig.loader')->__toString();
        $twigLoaderFilesystemDefinition = $container->getDefinition($twigLoaderFilesystemId);

        // Replaces native EasyAdmin templates
        $appBundleRefl = new \ReflectionClass(AppBundle::class);
        if ($appBundleRefl->isUserDefined()) {
            $appBundlePath = \dirname((string) $appBundleRefl->getFileName());
            $appTwigPath = dirname($appBundlePath).'/templates/bundles/EasyAdminBundle';
            $twigLoaderFilesystemDefinition->addMethodCall(
                'prependPath',
                [$appTwigPath, 'EasyAdmin']
            );
        }

        // Register EasyAdminExtension templates
        $easyAdminExtensionBundleRefl = new \ReflectionClass(EasyAdminExtensionBundle::class);
        if ($easyAdminExtensionBundleRefl->isUserDefined()) {
            $easyAdminExtensionBundlePath = \dirname((string) $easyAdminExtensionBundleRefl->getFileName());
            $easyAdminExtensionTwigPath = $easyAdminExtensionBundlePath.'/Resources/views';
            $twigLoaderFilesystemDefinition->addMethodCall(
                'prependPath',
                [$easyAdminExtensionTwigPath, 'EasyAdminExtension']
            );
        }
    }
}
```

create file `src/AppBundle.php`

```php
<?php

namespace App;

use App\DependencyInjection\Compiler\TwigPathPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container->addCompilerPass(new TwigPathPass());
    }
}
```

That's all!

**Comment by alterphp** [comment]
Thanks @phcorp for this feedback. This is indeed a way to achieve, maybe not the most dev-friendly. I'm working of making it more simple, through symfony project itself, or into EasyAdminExtension bundle.

**Comment by MakG10** [comment]
Another workaround if you feel like adding a compiler pass is too much for overriding just a layout:

```yaml
easy_admin:
    design:
        templates:
            layout: 'bundles/EasyAdminBundle/default/layout.html.twig'
```

Of course you'll still not be able to override other templates in EasyAdminBundle. The only templates available for override in yaml config are: layout, menu, paginator.

**Comment by alterphp** [comment]
@Gu3 @phcorp @MakG10 Can you try the branch of #115 and tell me if it fixes your issue ?
