### ISSUE TITLE
form_filters text

### ISSUE THREAD

**Issue by andrea-daru** [alterphp/EasyAdminExtensionBundle#111]
I can't figure out how to add a free text filter on a string field of the entity listed.
Is it possible to add a text filter (maybe with like operator)?

Thank you in advance! Great job!

**Comment by alterphp** [comment]
Hi @andrea-daru !

Have you tried this ?
`- { property: fieldname, type: text, operator: like }`

**Comment by andrea-daru** [comment]
Thank you! It works.
Maybe I'm wrong but I can't find it documented in the README.md.

**Comment by alterphp** [comment]
I added it just after my answer !
