### ISSUE TITLE
Feature Request: role: !ROLE_USER

### ISSUE THREAD

**Issue by ArminVieweg** [alterphp/EasyAdminExtensionBundle#112]
Hi!
It would be nice if I could tell e.g. a menu item that it should only be displayed when the user is **not** logged in. 

Maybe this is already possibile, but I just found the ``IS_AUTHENTICATED_ANONYMOUSLY`` role, and this is applied to **all** users.

In case this is not possible, I suggest two implementations:

1. ``role: '!ROLE_USER'`` so when the role starts with an exclamation mark, the validation result is negated
2. or a new option, like ``role_negate: true``, which negates the result if true

With this you can implement a Login button in navigation and replace it with Logout button, when the user logged in.

Thanks in advance!

**Comment by alterphp** [comment]
Hi @ArminVieweg !

Sorry for late answer. Dealing with negation on security features ... I prefer not starting in this way.

For your particular need, I think you should override the admin layout `main_menu_wrapper` block. WDYT ?

**Comment by ArminVieweg** [comment]
And when you implement "anonymous" as own pseudo role?

Solving this by template is possible, true. I'm wondering why the security package does not provide a real ROLE_ANONYMOUS only applying to not logged in users.

**Comment by alterphp** [comment]
Not authenticated => no role. It makes sense, roles are used to build access map, but is related to a user, with properties, not to nothing.

Do not check the role, check if there is an authenticated token in the token storage instead. Or you can also check if token is not granted ROLE_USER, but someone logged but with a disable account would match this criteria...
