### ISSUE TITLE
String filter as regular input and not choices list?

### ISSUE THREAD

**Issue by z01d** [alterphp/EasyAdminExtensionBundle#116]
I apologize if I have overlooked the answer somehow, but how can I filter an object by string value, (i.e. uuid)? The documentation gives an only option as pre-defined choices.

I'm looking for the similar behavior as in integer filter, i.e. "guessed filter is an integer input".

Thank you for your work!

**Comment by alterphp** [comment]
Hi @z01d !

Try `- { property: uid, type: text, operator: equals }`

**Comment by z01d** [comment]
Thank you, @alterphp, it worked!

**Comment by thi3rry** [comment]
@alterphp maybe you could provide a simple paragraph in README.md to document guessed input filter type text ?
