### ISSUE TITLE
AJAX Prev/Next embedded_list buttons insert the same page in place of the list

### ISSUE THREAD

**Issue by thi3rry** [alterphp/EasyAdminExtensionBundle#117]
**Version affected** : 2.x
**Step to reproduce :** 
* Add a embedded_list to your 'edit'
* click on "next" button for the embedded_list

**Problem** : The ajax request is done on the same page url that the actual page, this has the "inception" effect of loading the current page IN the current page with the layout.
The href of the A tag is not retrieving correctly. The A contains a span and e.target refers to this span.
**Solution** : Fix the retrieving of the href on the A tag by using e.currentTarget instead of e.target

**Comment by alterphp** [comment]
Fixed by #118
