### ISSUE TITLE
Roles does not protect when invalid id is given

### ISSUE THREAD

**Issue by ArminVieweg** [alterphp/EasyAdminExtensionBundle#120]
When you query a non-existing id, you get an error message instead of a redirection to login. When you enter an existing id, you get redirected.

The issue occures in vendor/easycorp/easyadmin-bundle/src/EventListener/RequestPostInitializeListener.php (line 76). 

Maybe this is a general issue, but I just realized that this happen and wanted to inform you :)

**Comment by alterphp** [comment]
Hi @ArminVieweg ! Thanks for this information. Indeed, this behavior gives hints to potential attackers... This is hard to fix in the extension bundle. This is the limit not having security features in original EasyAdmin. I know @javiereguiluz is working on it, so I think it's worth waiting EasyAdmin implementation of security layer.
