### ISSUE TITLE
reloadEmbeddedList's "e.target.href" may apply on <span> instead of <a>

### ISSUE THREAD

**Issue by ArminVieweg** [alterphp/EasyAdminExtensionBundle#122]
Hi,
I've build an own custom action (with own template) which includes an embedded list.

```
{% include '@EasyAdmin/includes/_include_embedded_list.html.twig' with {
    entity: 'AnEntityOnlyConfiguredForThisList',
    filters: [],
    sort: { field: 'id', direction: 'asc' }
} only %}
```

This works but the Javascript has problems to fetch the url used for the ajax request.

In HTML the "next page" link looks like this:

```
<a class="btn btn-secondary " href="/?entity=AnEntityOnlyConfiguredForThisList&amp;action=embeddedList&amp;sortField=id&amp;sortDirection=asc&amp;page=2">
    <span class="btn-label">Nächste</span> <i class="fa fa-angle-right"></i>
</a>
```

But for me ``e.target`` is (for any reason) not the link, it's `span.btn-label`. The script tries to get the href from the span, this results in undefined and only reloads the current page (which occures inception at the embedded list's position ;-) )

I've overwritten your global `reloadEmbeddedList` function and replaced

```
url: e.target.href,
```
with
```
url: $(this).attr('href'),
```

Because you are already using jQuery it shouldn't make a huge difference, but works for me also when using embedded list in a custom template.

Maybe you want to apply this fix, so I don't need to overwrite your JS anymore :)

I've tested with latest Google Chrome (73) on Windows 10.

**Comment by alterphp** [comment]
Hi @ArminVieweg !

Which version are you using ? I think this bug has been fixed by @thi3rry with #118 and is available from version 2.1.3.

**Comment by ArminVieweg** [comment]
Hey. I'm using v2.1.1.
But what is super weird now... composer update does not update to 2.1.3. The version constraint in composer.json is "^2.1". And packagist has the version 2.1.3. 

It updated the Symfony framework (from 4.2.5 to 4.2.7) but not your package... I've never had this behaviour before... But maybe it's symfony.lock related... 

I'll try to update and report when the issue is fixed.

**Comment by ArminVieweg** [comment]
Oh. The reason why the update has not been suggested was:

`league/uri-components 1.8.2 requires ext-intl * -> the requested PHP extension intl is missing from your system.`

**Comment by ArminVieweg** [comment]
Hm... Now I'm struggling with

> There are no registered paths for namespace "BaseEasyAdmin" in EasyAdminExtensionBundle:default:list.html.twig at line 1.

I would not expect such breaking changes in a bugfix update :/

**Comment by ArminVieweg** [comment]
Next issue occures in list view with this config:
```
            list:
                form_filters:
                    -   property: traeger
```

> Maximum function nesting level of '1000' reached, aborting!

When I remove this config, no exceptions.

**Comment by ArminVieweg** [comment]
Okay. The infinite loop was my own fault!
In my overwriting "bootstrap_4.html.twig" template I extended from "@EasyAdmin/form/bootstrap_4.html.twig". Missing exclamation mark here.

**Comment by ArminVieweg** [comment]
Great! Now the update works and the JS issue is fixed :)

**Comment by alterphp** [comment]
Glad you reached a working state !

**Comment by ArminVieweg** [comment]
Hi @alterphp,
I think I've discovered another bug with this javascript... it does apply always also when the "next" or "prev" link has `href="#"` and `class="disabled"`.

So when I click on a disabled paginator link, I get the current page injected to the embedded-list (inception). Can you confirm this?

I think you could fix this simply by modifying the selector from

`.on('click', '.list-pagination a', function (e) {`
to
`.on('click', '.list-pagination a:not(.disabled)', function (e) {`

**Comment by ArminVieweg** [comment]
The changed selector basically works, but a click on such links result in scolling up. So it would be better to always e.preventDefault() and do not execute the ajax request, when class "disabled" is set (or href is === '#')

**Comment by alterphp** [comment]
Thank you, it's fixed in master branch !
