### ISSUE TITLE
Type: embedded_list Add new option by modal in new and edit

### ISSUE THREAD

**Issue by gonzakpo** [alterphp/EasyAdminExtensionBundle#125]
Type: embedded_list Add new option by modal in new and edit

**Comment by alterphp** [comment]
Hi @gonzakpo ! Can you describe this feature more precisely please. I'm not sure to understand what you mean.

**Comment by parijke** [comment]
I think the ability to directly add children from the embedded_list? Sounds like a reasonable feature to. For example if you view an invoice with invoice_items as an embedded_list, that you can add invoice items directly from that view? (If that isn't possible already)

**Comment by alterphp** [comment]
This is a huge work to achieve that feature and making it generic. Not suitable for an extension bundle, only relevant in EasyAdmin itself.
