### ISSUE TITLE
Embedded list pagination issue

### ISSUE THREAD

**Issue by YosraHamza** [alterphp/EasyAdminExtensionBundle#134]
Hello,
Thanks for the great bundle.
I have an embedded list in the show view, when I click on the next page it brings the whole page in the embedded list section, sometimes it happens only when navigating after the first ajax call.

Thanks in advance.

**Comment by alterphp** [comment]
Which version of the bundle are you using ? Most of these issues have been fixed with v2.1.4.

**Comment by YosraHamza** [comment]
It was a fresh installation but because of some missing php extensions the 2.1.1 version was downloaded.
Thanks it is now working.
