### ISSUE TITLE
List filters CSS

### ISSUE THREAD

**Issue by carlespibernat** [alterphp/EasyAdminExtensionBundle#136]
Hi!

I'm using list filters and recently I've noticed that the CSS of the dropdown has been removed. I think that this was with the last update but I'm not sure. 

![alt text](https://i.ibb.co/Jjsv2P0/alterphp.jpg)

Does anyone have the same issue or knows how to solve it?

Thanks!

**Comment by alterphp** [comment]
Hi @carlespibernat.

- Is CSS file `bundles/easyadminextension/stylesheet/easyadmin-extension.css` loaded ?
- Did you override Twig `head_stylesheets` block from easyadmin layout ?

**Comment by carlespibernat** [comment]
Thanks! You were right, it was missing the easyadmin-extension.css CSS file.

Maybe this should be added to the documentation, I've searched if I was missing any CSS file and I didn't found it.

**Comment by alterphp** [comment]
This file is automatically loaded from the layout provided by the extension
bundle. Something in your project makes it unloaded. Track your admin
custom templates to find the culprit 😉

Le jeu. 30 mai 2019 à 12:34, carlespibernat <notifications@github.com> a
écrit :

**Comment by carlespibernat** [comment]
Thank! I'll check it!
