### ISSUE TITLE
Deprecation notice in Symfony 4.3

### ISSUE THREAD

**Issue by alex-bacart** [alterphp/EasyAdminExtensionBundle#137]
In Symfony 4.3 the deprecation notice is appearing:
```The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "easy_admin_extension" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.```

Because of [this code](https://github.com/alterphp/EasyAdminExtensionBundle/blob/master/src/DependencyInjection/Configuration.php#L21). The way it should be may be seen [here](https://github.com/EasyCorp/EasyAdminBundle/blob/master/src/DependencyInjection/Configuration.php#L18).

**Comment by alterphp** [comment]
Hi @alex-bacart !

I know, but this bundle is compatible from Symfony 4.1 (cf. https://github.com/alterphp/EasyAdminExtensionBundle/blob/master/composer.json) so it MUST keep the call this `root` method as the constructor did not exist yet in Symfony 4.1 (cf. https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php).

That's the purpose of the Symfony Backward Compatibility Policy (https://symfony.com/doc/current/contributing/code/bc.html#using-our-classes) : deprecate but keep compatible.

If you are annoyed by these messages, use the `weak_vendor` deprecation log level (in PHPUnit for example).
