### ISSUE TITLE
Embedded List type issue on ManyToMany

### ISSUE THREAD

**Issue by botjaeger** [alterphp/EasyAdminExtensionBundle#138]
embedded_list displays data when filters do not match instead of displaying "No result"

**Comment by botjaeger** [comment]
Im using symfony 4.3, and latest EasyAdminExtensionBundle

**Comment by botjaeger** [comment]
It just dont follow the filter options, with ManyToMany relationship

**Comment by alterphp** [comment]
List filters are not suitable for ManyToMany relations. List filters are currently under review for being integrated into the base EsayAdmin bundle (https://github.com/EasyCorp/EasyAdminBundle/commit/4c22387868cecaa3369e5ea4d6b3986266d4efce) so I am not going to maintain them on a long-term time lapse in this bundle.
