### ISSUE TITLE
Reference entity property in modal text

### ISSUE THREAD

**Issue by abdielcs** [alterphp/EasyAdminExtensionBundle#139]
There is some way to reference an entity property in the modal dialog in the list view? Like:

Are you sure you want to reserve the article "article-name"?

**Comment by alterphp** [comment]
If you are asking about the `#modal-confirm`, then you can customize the message in the `data-confirm` attribute of the link triggering the modal.

**Comment by abdielcs** [comment]
![Capture](https://user-images.githubusercontent.com/5825680/59361565-10a0c980-8d00-11e9-9c7e-618eba7050c1.PNG)

I would like in the message refer to the name of the item on which the action was executed, in the list view. Do you want to reserve the article "keyboard"?

**Comment by alterphp** [comment]
I see, it is not possible from configuration, only for a custom link in a template.

**Comment by alterphp** [comment]
If you master Twig, you can try to PR `Resources/views/default/includes/_actions.html.twig` to deal with placeholder (from `item` variable).
