### ISSUE TITLE
New and embeddedList

### ISSUE THREAD

**Issue by Gu3** [alterphp/EasyAdminExtensionBundle#146]
Hi !
Is it possible to have the "New" button directly inside the form view when we use the embedded list component ? 
Thank !

**Comment by cedric-ES** [comment]
or can you explain how add this button ?

**Comment by alterphp** [comment]
You can override '@EasyAdminExtension/default_embedded_list.html.twig' in order to add your custom stuff.

Put the following example code in `templates/bundles/EasyAdminExtensionBundle/default/embedded_list.html.twig` :

```
{% extends '@!EasyAdminExtension/default/embedded_list.html.twig' %}

{% block main %}
    CUSTOM STUFF
    {{ parent() }} 
{% endblock main %}

```
