### ISSUE TITLE
List filters broken after installing EasyAdminBundle v2.2.0

### ISSUE THREAD

**Issue by soefelix** [alterphp/EasyAdminExtensionBundle#147]
With the new version released two days ago, when using this bundle, there is an issue with the filters because it uses `filters` which is also used now by EAB.
My proposal would be to rename all `filters` by `form_filters` or `request_filters` depending of where it's used.
WDYT?

I use this bundle mainly for the role management so I could not say what will break after this change.

**Comment by alterphp** [comment]
Hi @soefelix !

I know that new **filters** feature of EasyAdmin is incompatible with EasyAdminExtension's one. For now, I can only limit EasyAdminBundle under v2.2.0 in composer.json. This is really disappointing but I have no time to work on it right now.

**Comment by xfifix** [comment]
@soefelix     
j'ai décoré le Subscriber qui posait problème :
 
App\EventSubscriber\PostQueryDecorateBuilderSubscriber:
        decorates: AlterPHP\EasyAdminExtensionBundle\EventListener\PostQueryBuilderSubscriber

**Comment by alterphp** [comment]
@xfifix can you show the code of your decorator ? this wil help me to provide a solution and unlock the upgrade of EasyAdmin version, that I locked since cc256beab804f9b0484b62fd9c2590399e4a8d63

**Comment by xfifix** [comment]
I didn't find a solution to fix the applyRequestFilter for the moment. I want just use the role management and filter of EAB so My decorate do nothing..

**Comment by soefelix** [comment]
@alterphp in fact with the proposal of @xfifix, there is two things to do:
Create an empty file: 
```php
<?php
declare(strict_types=1);

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class PostQueryDecorateBuilderSubscriber implements EventSubscriberInterface
{
    /**
     * @return array The event names to listen to
     */
    public static function getSubscribedEvents(): array
    {
        return [];
    }
}
```

add to the services.yaml
```yaml
    App\EventSubscriber\PostQueryDecorateBuilderSubscriber:
        decorates: AlterPHP\EasyAdminExtensionBundle\EventListener\PostQueryBuilderSubscriber
```

It's only a workaround because:
- The EAB filter will work
- The filter icon from this bundle will be visible as shown in the screenshot
![image](https://user-images.githubusercontent.com/8562588/60208629-0b439300-9859-11e9-9dfd-0660f3468d3b.png)
- I don't see how that logic can be used in this bundle and avoiding BC break at the same time (I don't know everything allowed by symfony so maybe you will have some ideas)

WDT if for the next release (3.* or 2.2.* depending on semver) we remove all code related to filter implemented in this bundle?
As you don't have much time currently, I could start a PR and doing it step by step on your guidance so we could soon release a new version.

**Comment by mkebza** [comment]
I think, because it will be big BC break, would make sense to remove filters and mark it as 3.* so people  can stay on old one if they have builded infrastructure already. But in general agree with @soefelix . Remove filter related code and make new version.

**Comment by alterphp** [comment]
So removing embedded lists too... Because they rely on it.

**Comment by mkebza** [comment]
Embedables are one of killer features for me for this. Would be nice to keep that.

**Comment by alterphp** [comment]
I think so as well. Last version of extension does not allow to install
v2.2.0 of Easyadmin. Do you confirm?

**Comment by mkebza** [comment]
yes i can confirm that. 

For embeddable. What about using the way, that in definition of embeddable we replace filters with DQL and will be able to insert DQL snippet over there insted of filters. This might be able to get rid of filters while keeping embeddables. But i didnt check propertly to the code, just idea.

**Comment by alterphp** [comment]
See PR #166
