### ISSUE TITLE
Make EasyAdmin filters compatible

### ISSUE THREAD

**Issue by gisostallenberg** [alterphp/EasyAdminExtensionBundle#153]
Are there any plans on making EasyAdmin filters compatible instead of just avoid the installation of v2.2.0+ as is done in https://github.com/alterphp/EasyAdminExtensionBundle/releases/tag/v2.1.7?

How can I help?

**Comment by alterphp** [comment]
Hi @gisostallenberg !

The plan is to use new EasyAdmin filters and remove them from the extension.

But ... embedded lists relies on dynamic list filters. So it requires to migrate embedded list feature to the new filters implementation. For now, list filters from EasyAdmin must be configured, you cannot put a filter in your HTTP request that is not defined in `easy_admin` config.

What's the plan :

- Make EasyAdmin filtering totally dynamic, and the configuration of list filters form would only be used to build the form, (ping @javiereguiluz @yceruto WDYT ?),
- Migrate embedded list to the new filters implementation.

Another main feature that seems being implemented to EasyAdmin : role-based security. This feature will be removed from the extension.

And as I know that embedded list is in a TODO list of EasyAdmin team, I guess this extension will become useless (and that's good!).

To be honest, I have no time this summer to stay tuned on EasyAdmin evolutions and this plan is still "abstract" :-D I think working on EasyAdmin to implement the first item of the plan would help ;-)

**Comment by qcho** [comment]
In the meantime I've sent a PR to make **EAEB** & **EAB** filters compatible.

**Comment by yceruto** [comment]
> Make EasyAdmin filtering totally dynamic, and the configuration of list filters form would only be used to build the form, (ping @javiereguiluz @yceruto WDYT ?),

Not sure what do you mean with make EasyAdmin filtering totally dynamic... :/

**Comment by alterphp** [comment]
Hi @yceruto !

When I checked the dynamic filter feature on EAB, only filters configured in the EasyAdmin config were handled by the query builder.
The same HTTP request, with included filters as GET params, but without the list filters configuration should filter the list as well, IMHO.

Is it something you'd expect from EAB list filters ?

**Comment by yceruto** [comment]
> The same HTTP request, with included filters as GET params, but without the list filters configuration should filter the list as well, IMHO.

How is it supposed to work without a preconfiguration? It seems fragile and a bit magic/convention to me.

**Comment by alterphp** [comment]
Most of filters usage is an equality on a relation or a property, the idea is to make them implicit, like auto filters in Excel => they are fragile indeed but very efficient.

Filtering a list requires to produce some config in both cases in EAB (if i'm up to date with last features that is not sure) : dql_filter and list filters. My expectation is to quickly display a list just by adding some simple filters to an HTTP query. It's obviously restricted to **equality** (and why not **contains** for iterable properties). Something like this : https://github.com/alterphp/EasyAdminExtensionBundle/blob/master/src/EventListener/PostQueryBuilderSubscriber.php#L52

**Comment by alterphp** [comment]
@gisostallenberg see #166

**Comment by alterphp** [comment]
Fixed by #166 => tagged as `v3.0.0`
