### ISSUE TITLE
Allow Symfony 5

### ISSUE THREAD

**Issue by cobyl** [alterphp/EasyAdminExtensionBundle#162]

**Comment by alterphp** [comment]
If you wanna try, you can use this development branch : dev/ea-2.2-and-upper

**Comment by Plopix** [comment]
Are we sure that is working? 
This constraint seems to block the update
https://github.com/alterphp/EasyAdminExtensionBundle/blob/master/composer.json#L20

https://github.com/EasyCorp/EasyAdminBundle/releases/tag/v2.3.3

**Comment by alterphp** [comment]
Hi @Plopix !

Please see the PR #166 and the branch `dev/ea-2.2-and-upper`. It should be ok now. I'm waiting some feedback about the way to tag this new version as there is a BC break to take in account...
