### ISSUE TITLE
how Much Time To remove easyadmin-bundle top version limit in master branch ??

### ISSUE THREAD

**Issue by kodedara** [alterphp/EasyAdminExtensionBundle#168]
Need Install But Version Issue ....
i have easyadmin 2.3.2

**Comment by alterphp** [comment]
As long as it will take to make it compatible !!

**Comment by alterphp** [comment]
If you had searched before posting your rude inquiry, you should have found a branch that holds changes you'd like to get.

**Comment by kodedara** [comment]
when  i run This Command got ErrorException strpos(): Empty needle  
php7.2 /usr/local/bin/composer req alterphp/easyadmin-extension-bundle: "dev/ea-2.2-and-upper"

Exception trace:
Exception trace:
 () at /opt/lampp/htdocs/mfa-backend/vendor/symfony/flex/src/PackageResolver.php:120
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 strpos() at /opt/lampp/htdocs/mfa-backend/vendor/symfony/flex/src/PackageResolver.php:120
 Symfony\Flex\PackageResolver->throwAlternatives() at /opt/lampp/htdocs/mfa-backend/vendor/symfony/flex/src/PackageResolver.php:64
 Symfony\Flex\PackageResolver->resolve() at /opt/lampp/htdocs/mfa-backend/vendor/symfony/flex/src/Command/RequireCommand.php:42
 Symfony\Flex\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:258
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24
@alterphp did explain me how to resolve this error 
thanks

**Comment by alterphp** [comment]
Put that line in the `require` section of your `composer.json` and then run `composer update` :
`alterphp/easyadmin-extension-bundle: "dev-dev/ea-2.2-and-upper as 2.2.0"`
