### ISSUE TITLE
ROLES menu item dont work with symfony 4.4

### ISSUE THREAD

**Issue by rubenGit** [alterphp/EasyAdminExtensionBundle#170]
Does not hide menu items when the user does not have permission to see that section

Example:

easy_admin.yml

menu:
- { entity: 'Establishment', icon: 'building', role:  [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
- { entity: 'Device', icon: 'tv', role: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_USER]}
- { entity: 'Content', icon: 'book', role: ROLE_ADMIN }

CURRENT USER IN SESSION
Roles | [▼   "ROLE_USER" ]

PACKAGES COMPOSER:
        "alterphp/easyadmin-extension-bundle": "^3.0",
        "easycorp/easyadmin-bundle": "^2.3",

**Comment by rubenGit** [comment]
Its with the key: permission: 
- { entity: 'Device', icon: 'tv', permission: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_USER]}
- { entity: 'Content', icon: 'book', permission: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_USER] }

But it does not appear in the github documentation

**Comment by alterphp** [comment]
This feature is now covered by __EasyAdmin__ with permission keyword. Branch `3.x` of __EasyAdminExtension__ has removed former implementation based on `role` keyword.

The README of EasyAdminExtension has been updated in the `master` branch.
