### ISSUE TITLE
List action with "template" property doesn't work

### ISSUE THREAD

**Issue by PastisD** [alterphp/EasyAdminExtensionBundle#178]
Hello,

With this bundle, we can't add an action in list with "template" option (https://symfony.com/doc/2.x/bundles/EasyAdminBundle/tutorials/custom-actions.html#custom-templates-for-actions)

**Comment by alterphp** [comment]
I guess custom template for actions is a new feature of EasyAdmin 2.x.

Can you make a pull request to backport the feature ?

**Comment by PastisD** [comment]
I made a very dirty quickfix. If i have time to think about it i'll make a PR :P

**Comment by vatri** [comment]
I have same problem.

When will this be released?
