### ISSUE TITLE
Columns filter for embedded lists

### ISSUE THREAD

**Issue by LPPierre** [alterphp/EasyAdminExtensionBundle#18]
Add an option taking listed entity properties as parameters and filtering corresponding columns.

**Comment by alterphp** [comment]
I did not find a suitable way to match columns that to query filters...

Maybe in a future version of EasyAdmin (let's wait the 2.0).

**Comment by alterphp** [comment]
This is achieved by #133.

Use `hidden_fields` option to hide original list columns.
