### ISSUE TITLE
Entities using doctrine inheritance not filtered in embedded list

### ISSUE THREAD

**Issue by friizer** [alterphp/EasyAdminExtensionBundle#180]
I fixed that on line 104 of EmbeddedListHelper.php 

if (($parentEntityFqcn === $assoc['targetEntity'] || is_subclass_of($parentEntityFqcn, $assoc['targetEntity'])) && $parentEntityProperty === $assoc['inversedBy']) {

**Comment by alterphp** [comment]
@friizer Can you test the PR in order to merge and close this issue ?
