### ISSUE TITLE
EasyAdmin v3.x compatibility

### ISSUE THREAD

**Issue by isaring** [alterphp/EasyAdminExtensionBundle#185]
Hi, 

As a highly satisfied user of your bundle, I was wondering if you were planning to make it compatible with the new EasyAdmin v3.x (released in june) ? 

At the moment, if I run a `composer update` while upgrading `easycorp/easyadmin-bundle`, it says : 

> Problem 1
>     - alterphp/easyadmin-extension-bundle v3.0.2 requires easycorp/easyadmin-bundle ^2.2.2 -> satisfiable by easycorp/easyadmin-bundle[2.x-dev, v2.2.2, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9] but these conflict with your requirements or minimum-stability.
>     - alterphp/easyadmin-extension-bundle v3.0.1 requires easycorp/easyadmin-bundle ^2.2.2 -> satisfiable by easycorp/easyadmin-bundle[2.x-dev, v2.2.2, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9] but these conflict with your requirements or minimum-stability.
>     - alterphp/easyadmin-extension-bundle v3.0.0 requires easycorp/easyadmin-bundle ^2.2.2 -> satisfiable by easycorp/easyadmin-bundle[2.x-dev, v2.2.2, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9] but these conflict with your requirements or minimum-stability.
>     - alterphp/easyadmin-extension-bundle v3.0.1 requires easycorp/easyadmin-bundle ^2.2.2 -> satisfiable by easycorp/easyadmin-bundle[2.x-dev, v2.2.2, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9] but these conflict with your requirements or minimum-stability.
>     - Installation request for alterphp/easyadmin-extension-bundle ^3.0 -> satisfiable by alterphp/easyadmin-extension-bundle[v3.0.0, v3.0.1, v3.0.2].

Can't wait to know more about the future !

Regards,

**Comment by alterphp** [comment]
Hi @isaring and thank you for your nice message.

For now, I don't plan any upgrade. The main reason of this bundle is providing **embedded list** feature that is on the roadmap of EasyAdmin bundle. Due to the cost of maintaining this bundle and the cost of EasyAdmin v3 bundle, I'm not planning any upgrade.
