### ISSUE TITLE
Easy Admin 3 Compatibility

### ISSUE THREAD

**Issue by janthomas89** [alterphp/EasyAdminExtensionBundle#187]
Thank you for your great Easy Admin extensions. Especially the embedded lists are very valuable for our admin dashboard. As Easy Admin 3 was releasesd in June 2020, I am curious if there are any plans regarding Easy Admin 3 compatibility?

Thank you!

**Comment by isaring** [comment]
Hi @janthomas89 

I already ask @alterphp about that last month and, unfortunately, there is no plan to upgrade this bundle (at the moment).

See: https://github.com/alterphp/EasyAdminExtensionBundle/issues/185#issuecomment-668263834
