### ISSUE TITLE
Is this compatible with EasyAdmin 3 ?

### ISSUE THREAD

**Issue by kconde2** [alterphp/EasyAdminExtensionBundle#188]

**Comment by parijke** [comment]
Well, the readme suggests ^2.2.2 but I don't think so as this depends on yaml configuration

**Comment by isaring** [comment]
Hi @kconde2 :) 

As mentioned in #185 and #187, there is no plan to make this bundle work with EasyAdmin3.

Regards,

**Comment by kconde2** [comment]
I'm closing this issue. Thanks for you answers.
