### ISSUE TITLE
There is no extension able to load the configuration for "easy_admin_bundle  

### ISSUE THREAD

**Issue by josephzhao** [alterphp/EasyAdminExtensionBundle#19]
There is no extension able to load the configuration for "easy_admin_bundle  
!!    " (in /NetBeansProjects/map2u_react/config/packages/easy_admin.yaml). Looke  
!!    d for namespace "easy_admin_bundle", found "framework", "doctrine_cache", "  
!!    doctrine", "doctrine_fixtures", "sensio_framework_extra", "monolog", "doctr  
!!    ine_migrations", "security", "swiftmailer", "twig", "white_october_pagerfan  
!!    ta", "debug", "web_profiler", "web_server", "easy_admin", "stof_doctrine_ex  
!!    tensions", "uerka_translation_form", "easy_deploy", "easy_admin_extension"  

in the esay_admin.yaml file

easy_admin_bundle:
    resource: '@EasyAdminExtensionBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation

**Comment by alterphp** [comment]
My mistake, I just updated the README to fix documentation.

Replace `easy_admin_bundle` in the YAML file with `easy_admin`. This should fix this.

**Comment by justincletus** [comment]
@alterphp It is not working for me symfony 4 project.

**Comment by alterphp** [comment]
Hi ! The answer is in the error message : the config entry point is wrong.

Le ven. 14 juin 2019 à 07:34, Justin Cletus <notifications@github.com> a
écrit :
