### ISSUE TITLE
Toogle switch on column disappear on page change

### ISSUE THREAD

**Issue by karol-gontarski** [alterphp/EasyAdminExtensionBundle#20]
![bug](https://user-images.githubusercontent.com/844448/36582732-eeace3b6-1872-11e8-8718-55fa08deff15.gif)

**Comment by alterphp** [comment]
Fixed by https://github.com/alterphp/EasyAdminExtensionBundle/commit/521c86ed8ea3a4c04e9d62f50e0123dca41ac49e

**Comment by karol-gontarski** [comment]
thx!
