### ISSUE TITLE
Passing an array of Security attributes to AuthorizationChecker::isGranted is deprecated since Symfony 4.4

### ISSUE THREAD

**Issue by vilcar** [alterphp/EasyAdminExtensionBundle#200]
For version 2.x
Passing an array of Security attributes to AuthorizationChecker::isGranted is deprecated since Symfony 4.4
To avoid this, EasyAdmin checks first if it is an array, and in that case, it checks if at least one is valid. as you can see here for example.
https://github.com/EasyCorp/EasyAdminBundle/blob/v2.3.2/src/Security/AuthorizationChecker.php#L32

The problem I have found at least here.
https://github.com/alterphp/EasyAdminExtensionBundle/blob/v2.2.0/src/Helper/MenuHelper.php#L53

Some services must implement `easyadmin.security.authorization_checker` insteadof `security.authorization_checker`

**Comment by themark147** [comment]
that should be helpful for now

**services.yaml**
```
AlterPHP\EasyAdminExtensionBundle\Security\AdminAuthorizationChecker:
      arguments:
        $authorizationChecker: "@easyadmin.security.authorization_checker"
```
