### ISSUE TITLE
Symfony 5 & easyadmin 3 is not working

### ISSUE THREAD

**Issue by ngongoll** [alterphp/EasyAdminExtensionBundle#201]
Hi guys

is there a chance to get this working on symfony5 and easyadmin3? 
i'm getting this error.

Problem 1
    - alterphp/easyadmin-extension-bundle[v3.1.0, ..., v3.1.1] require php ^7.1.3 -> your php version (8.0.12) does not satisfy that requirement.
    - alterphp/easyadmin-extension-bundle[v3.1.2, ..., 3.1.11] require easycorp/easyadmin-bundle ^2.3.4 -> found easycorp/easyadmin-bundle[v2.3.4, ..., v2.3.15] but it conflicts with your root composer.json require (^3).
    - Root composer.json requires alterphp/easyadmin-extension-bundle ^3.1 -> satisfiable by alterphp/easyadmin-extension-bundle[v3.1.0, ..., 3.1.11].

**Comment by ucay** [comment]
There's no plan to support Easy Admin 3.x

#196
