### ISSUE TITLE
Won't install on PHP 8.1.4

### ISSUE THREAD

**Issue by VariantT505** [alterphp/EasyAdminExtensionBundle#207]
Doesn't want to install cause my PHP version is not recognized, and cause... well, it wants a specific version of easyadmin-bundle and sadly, I have this exact same version (?).

    - alterphp/easyadmin-extension-bundle[v3.1.0, ..., v3.1.1] require php ^7.1.3 -> your php version (8.1.4) does not satisfy that requirement.
    - alterphp/easyadmin-extension-bundle[v3.1.2, ..., v3.1.14] require easycorp/easyadmin-bundle ^2.3.4 -> found easycorp/easyadmin-bundle[v2.3.4].

**Comment by sxsws** [comment]
not compatible with symfony 6

**Comment by alterphp** [comment]
3.1.x allows PHP 8 in its last versions. Symfony 6 will be allowed from 3.2.0
