### ISSUE TITLE
How to overwrite embedded_list.html template ?

### ISSUE THREAD

**Issue by karol-gontarski** [alterphp/EasyAdminExtensionBundle#21]

**Comment by alterphp** [comment]
In Symfony 4, create the template `templates/bnudles/EasyAdminExtensionBundle/default/embedded_list.html.twig` and put your code as following :

```twig
{% extends '@EasyAdmin/default/embedded_list.html.twig' %}

{% block main %}
    DO WHAT YOU WANT
{% endblock main %}

```

Hope it helps !

**Comment by karol-gontarski** [comment]
`templates/**bundles**/EasyAdminExtensionBundle/default/embedded_list.html.twig`
