### ISSUE TITLE
Posibility to disable open.new_tab button (other then overwriting template :) )

### ISSUE THREAD

**Issue by karol-gontarski** [alterphp/EasyAdminExtensionBundle#22]

**Comment by alterphp** [comment]
Fixed by https://github.com/alterphp/EasyAdminExtensionBundle/commit/34107db6f2cb4283d5bd19e70b7cb1392e1bb160

By overriding the template and empty this new block, it should be OK

**Comment by alterphp** [comment]
Hi @karol-gontarski 

I've added a config option to globally hide the "Open in new tab link" :

See the following config :

```
easy_admin_extension:
    embedded_list:
        open_new_tab: false
```
