### ISSUE TITLE
Override easyadmin list

### ISSUE THREAD

**Issue by eclyptox** [alterphp/EasyAdminExtensionBundle#25]
I am on symfony 3.4 and I have EasyAdminBundle list overrided. But if I add EasyAdminExtensionBundle, the TwigPathPass is overriding this and using original list twig file.

How can I achieve this?

Thanks

**Comment by alterphp** [comment]
Hi,

That's a bug.

Thanks for report,

**Comment by alterphp** [comment]
Hi @eclyptox !

I've investigated and it seems like EasyAdmin does not use basic Symfony template inheritance.

With Symfony 4, I managed to override the list template (and keep EasyAdminExtension list template add-ons) by creating a file `templates/easy_admin/list.html.twig` :

```twig
{% extends '@EasyAdmin/default/list.html.twig' %}

{% block content_title_wrapper %}
  XXXXXXXXXXXXXXXXX
  {{ parent() }}
  XXXXXXXXXXXXXXXXX
{% endblock %}

```

With Symfony 3.x, I expect you can get the same behavior by putting the content in a file `app/Resources/easy_admin/list.html.twig`.

Please let me know if it works !

**Comment by eclyptox** [comment]
Thanks @alterphp but it is not working. WIth EasyAdminBundle I override with this path: `app/Resources/EasyAdminBundle/views/default/list.html.twig`. I have tried yours also: `app/Resources/easy_admin/list.html.twig`, but it does not work either. I think TwigPathPass is overriding symfony overriding.

**Comment by alterphp** [comment]
I think I forgot a sub-path, it's `app/Resources/views/easy_admin/list.html.twig` ? Clear cache before trying.

**Comment by alterphp** [comment]
Have a look at the method `processEntityTemplates` of class `EasyCorp\Bundle\EasyAdminBundle\Configuration\TemplateConfigPass`. You can see that EasyAdmin template override strategy is not the basic Symfony one.

**Comment by eclyptox** [comment]
Wow!! That's it! Now it is working.

**Thanks**. This module is awesome.

**Comment by alterphp** [comment]
:+1:

**Comment by Amunak** [comment]
Hello, so while this behavior isn't technically a bug it should either adhere to standard Symfony template overriding *or* this behavior should be documented.

I spent way too much time figuring out why the override doesn't work and now I find out that it does exists; it's just non-standard.

Something as simple as mentioning this in the Readme would be great.

**Comment by alterphp** [comment]
HI @Amunak !

Sorry I took so much time to answer, I did not see your comment in my notifications.

I'm not sure to understand what is non-standard. I'd like your explanation to understand what you expect as the standard and what you had to do to make it work. The original issue is due to the EasyAdmin bundles dealt with template inheritance in the 1.x branch, but your comment let me think there is something non-standard in the EasyAdminExtension bundle.

Please let me know !

**Comment by Amunak** [comment]
To be honest I no longer remember what specifically was the issue.

I believe I wanted to override and extend some EasyAdmin/EasyAdminExtension template and nothing I tried worked, until I read your [comment](https://github.com/alterphp/EasyAdminExtensionBundle/issues/25#issuecomment-378249846). From that method I managed to figure out how to do the overriding.

You have a comment there:
```php
        // first, resolve the general template overriding mechanism
        // 1st level priority: easy_admin.entities.<entityName>.templates.<templateName> config option
        // 2nd level priority: easy_admin.design.templates.<templateName> config option
        // 3rd level priority: @EasyAdmin/default/<templateName>.html.twig
```

I suggest you put this anywhere in the readme, that'd probably be helpful to others as well.

**Comment by alterphp** [comment]
Ok, but code you are pointing is part of EasyAdmin bundle, not EasyAdminExtension bundle. That's why you should address your issue/request to it ;-)
