### ISSUE TITLE
Loading bunde in Symfony 4.x

### ISSUE THREAD

**Issue by mdolores85** [alterphp/EasyAdminExtensionBundle#32]
Hi, 

I'm using Symfony Flex with Symfony 4.1 in my project. Since I saw there's no recipe to install the bundle I tried to manually load it adding 

` AlterPHP\EasyAdminExtensionBundle\EasyAdminExtensionBundle::class => ['all' => true],` 

in ` bundles.php `, which gives me the next error:

(1/1) ClassNotFoundException
Attempted to load class "EasyAdminExtensionBundle" from namespace "AlterPHP\EasyAdminExtensionBundle".
Did you forget a "use" statement for another namespace?

Any hint about how to use it with Flex? Thanks.

**Comment by alterphp** [comment]
Hi,

Did you require the package with composer ?

**Comment by alterphp** [comment]
closing as no feedback provided by issuer

**Comment by anthonyptetlow** [comment]
I am also having this same issue. I required the package with composer. I am using symfony flex with symfony v4.1 and easy admin bundle v2.1.1

**Comment by alterphp** [comment]
Hi @anthonyptetlow !

I don't understand this bug. I encountered something similar because of composer autoload that did not work as expected.

Try to run this command `composer dump-autoload -o` and tell me if it fixed your bug.
