### ISSUE TITLE
MenuIndex error when has no role

### ISSUE THREAD

**Issue by eclyptox** [alterphp/EasyAdminExtensionBundle#34]
Easyadmin assigns a menuIndex and a submenuIndex to each menu item. In this bundle if you have no role for viewing that entity, the menu item is not displayed. but the menuIndex is not changed.
So if you click on the next item. It puts active the next item in the menu. I think I am not explaining me as well as I want. Let me show in some pictures.

- Stats -> menuIndex: 0
- Client -> menuIndex: 1
- User -> menuIndex: 2
- Ticket -> menuIndex: 3
- Client -> menuIndex: 4
![captura de pantalla de 2018-06-14 15 42 43](https://user-images.githubusercontent.com/710096/41415931-010bd62e-6fea-11e8-8548-081a325a370a.png)
This one is correct. You enter "User" and it activates "user" menu item.

- Stats -> menuIndex: 0
- Client -> menuIndex: 1
- Ticket -> menuIndex: 3
- Client -> menuIndex: 4
![captura de pantalla de 2018-06-14 15 44 11](https://user-images.githubusercontent.com/710096/41415932-012be16c-6fea-11e8-82d0-83d4be029757.png)
When you have no ROLE for "user" if you enter "Ticket" it jumps one number and highlights the following item.

**Comment by alterphp** [comment]
Hola @eclyptox !

Side-effect of role-based menu pruning indeed. Would you write a (functional) test that highlights this bug ? This could be an additional test in https://github.com/alterphp/EasyAdminExtensionBundle/blob/master/tests/Controller/UserRolesTest.php.

**Comment by eclyptox** [comment]
Sorry, but I was triying with no success. I was looking for the .active class. Your test is better. Good job.
