### ISSUE TITLE
Embedded list in show action

### ISSUE THREAD

**Issue by sbeff** [alterphp/EasyAdminExtensionBundle#37]
Hi, can I add the embedded list in the show action? I managed to do that just in the edit action. Thanks a lot!

**Comment by alterphp** [comment]
Hi @sbeff,

I'm looking for someone to test the branch where it is implemented (#10 ). Can you test the branch `feature/embedded-lists-show` and give me your feedback ?

**Comment by sbeff** [comment]
Sure, I'll give it a try. Thanks!

**Comment by alterphp** [comment]
Thanks !

**Comment by sbeff** [comment]
It's working great for me! 👍 I'll test it a couple more times. Are you having any kind of issue with this feature? Thanks.

**Comment by alterphp** [comment]
No issue, but I don't use show views so I wanted someone else feedback ;-)

**Comment by alterphp** [comment]
I close this issue and merge the PR.

Thanks for feedback !
