### ISSUE TITLE
Display specific columns in embedded_list

### ISSUE THREAD

**Issue by jarngotostos** [alterphp/EasyAdminExtensionBundle#41]
Hello. Thank you for this amazing work of yours.
Is there a way that **`embedded_list`** can specify which `columns` to display?

**Comment by alterphp** [comment]
Hello, and thank you for support.

`embedded_list` is intended to match `list` configuration so you must define another entity entry with its own list configuration (its different columns). Defining specific columns for embedded_list would not be a feature, it would change its intention.

The only column change I'd like to implement is to hide the column referencing the parent entity. For example, if you embed the list of animals in a zoo on the zoo SHOW view, you don't need the `zoo` column in the embedded_list of animals...
