### ISSUE TITLE
bug: Can't use EasyAdminExtensionBundle with EasyAdmin v1.17.14

### ISSUE THREAD

**Issue by SulivanDotEu** [alterphp/EasyAdminExtensionBundle#51]
Hello,

I try to install the Extension bundle with a fresh new project but Composer won't let me do that : 

        composer require alterphp/easyadmin-extension-bundle
        Using version ^1.2 for alterphp/easyadmin-extension-bundle
        ./composer.json has been updated
        Loading composer repositories with package information
        Updating dependencies (including require-dev)
        Your requirements could not be resolved to an installable set of packages.
    
        Problem 1
    - Conclusion: don't install alterphp/easyadmin-extension-bundle v1.2.7
    - Conclusion: don't install alterphp/easyadmin-extension-bundle v1.2.6
    - Conclusion: don't install alterphp/easyadmin-extension-bundle v1.2.5
    - Conclusion: don't install alterphp/easyadmin-extension-bundle v1.2.4
    - Conclusion: don't install alterphp/easyadmin-extension-bundle v1.2.3
    - Conclusion: don't install alterphp/easyadmin-extension-bundle v1.2.2
    - Conclusion: don't install alterphp/easyadmin-extension-bundle v1.2.1
    - Conclusion: remove pagerfanta/pagerfanta v2.0.1
    - Installation request for alterphp/easyadmin-extension-bundle ^1.2 -> satisfiable by alterphp/easyadmin-extension-bundle[v1.2, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7].
    - Conclusion: don't install pagerfanta/pagerfanta v2.0.1
    - alterphp/easyadmin-extension-bundle v1.2 requires pagerfanta/pagerfanta ~1.0,>=1.0.1 -> satisfiable by pagerfanta/pagerfanta[v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.1.0].
    - Can only install one of: pagerfanta/pagerfanta[v1.0.1, v2.0.1].
    - Can only install one of: pagerfanta/pagerfanta[v1.0.2, v2.0.1].
    - Can only install one of: pagerfanta/pagerfanta[v1.0.3, v2.0.1].
    - Can only install one of: pagerfanta/pagerfanta[v1.0.4, v2.0.1].
    - Can only install one of: pagerfanta/pagerfanta[v1.0.5, v2.0.1].
    - Can only install one of: pagerfanta/pagerfanta[v1.1.0, v2.0.1].
    - Installation request for pagerfanta/pagerfanta (locked at v2.0.1) -> satisfiable by pagerfanta/pagerfanta[v2.0.1].
    
    
        Installation failed, reverting ./composer.json to its original content.

This is because EasyAdminBundle use pagerfanta ~2.0 but not ExtensionBundle. I suggest to use 2.0 version. Is this doable? Should I/We use a different approach?

I'm here to help if needed.

**Comment by SulivanDotEu** [comment]
By the way, it is working on master branch so I believe it is a work in progress.

**Comment by alterphp** [comment]
Yes, master has the fix. It is not tagged yet.

Le sam. 25 août 2018 à 11:51, Ellis Benjamin <notifications@github.com> a
écrit :

**Comment by alterphp** [comment]
@SulivanDotEu It is now tagged with v1.2.8

**Comment by SulivanDotEu** [comment]
@alterphp thank you
