### ISSUE TITLE
List filters : new operators

### ISSUE THREAD

**Issue by alterphp** [alterphp/EasyAdminExtensionBundle#64]
Adds followinf filters operators :
- greater than
- greater than or equal
- lower than
- lower than or equal

**Comment by CheapHasz** [comment]
I am willing to implement that feature : 

Would a system using improbable prefixes be agreeable to you ?

I was thinking about a form type adding a `_>` /   `_>=` prefix to the value, which would allow the PostQueryBuilderSubscriber->filterQueryBuilder to correctly configure the $filterDqlPart with the operator.

**Comment by CheapHasz** [comment]
I tried tinkering with it, and got stuck when I realized that the QueryBuilder is handled before the form, rendering any usage of FormEvents or Transformer moot.

My next idea was to somehow acces the BackendConfig from the ConfigManager while filtering the QueryBuilder and handle everything via yaml config.

Any suggestion would be appercitaed

**Comment by alterphp** [comment]
Hi @CheapHasz !

Adding such new operators seems pretty simple. I would add cases in `PostQueryBuilderSubscriber::filterQueryBuilder` method.

- _GT: strictly greater than
- _GTE: greater than or equal
- _LT: strictly less than
- _LTE: less than or equal

I don't think those new operators would require any other changes, or I miss something ? If my suggestion does match your needs, I would be glad to welcome you as a new contributor ;-)

**Comment by CheapHasz** [comment]
The prefixes and the filtering would work, sure.

My problem was : how do we add these prefixes to the input value? 
As it stands, we can't use anything form related, as the querybuilder is filtered and paginated before the form filter is handled.

And I don't think that we can reasonably expect users to correctly type obscure prefixes in the inputs.

That's why I was thinking about about checking the config, as it would the be the most convenient place for developers to configure the behaviour

**Comment by alterphp** [comment]
You're right...

Working on handling list filters form makes sense !

**Comment by gonzakpo** [comment]
if we add
https://github.com/lexik/LexikFormFilterBundle
?

**Comment by CheapHasz** [comment]
Ok I see you have started to work on the form filter handling, great. 

Once finished, I'll be able to quickly add operator form fields.

Please hit me up if there is anything I can do to help that feature come to fruition.

**Comment by alterphp** [comment]
Hi @CheapHasz !

I get the error i got at first implementation : in Travis CI, `csrf_protection` form option is not allowed and tests fails because I explicitely disable csrf_protection in `ListFormFiltersHelper::getListFormFilters` method. Tests are going well on my local environment...

I'm debugging Travis to understand differences.

Any clue/idea/solution is of course welcomed !

**Comment by alterphp** [comment]
@CheapHasz PR merged in master. List filters form is now submitted to symfony level.

**Comment by CheapHasz** [comment]
Ok great, I'll resume working on the operators shortly then

**Comment by alterphp** [comment]
Being fixed by #92

**Comment by alterphp** [comment]
Fixed in v2.1.0
