### ISSUE TITLE
Default Filters

### ISSUE THREAD

**Issue by aequasi** [alterphp/EasyAdminExtensionBundle#65]
Is it possible to define default filters?

**Comment by aequasi** [comment]
Filters that are selected by default. (like, by default, when viewing an entity, i only want to see enabled ones)

**Comment by alterphp** [comment]
If you mean `list form filters`, the form method is GET so you can pass set parameters in the URL :

`https://example.com/admin/entity=Page&action=list&form_filters[status]=published&form_filters[categories][]=category1&form_filters[categories][]=category2`

Filter **status** will be preset on `published` and filter **categories** will set `category1` and `category2`.
