### ISSUE TITLE
EasyCorp\Bundle\EasyAdminBundle\Form\Util\FormTypeHelper

### ISSUE THREAD

**Issue by gonzakpo** [alterphp/EasyAdminExtensionBundle#74]
Version master:

Attempted to call an undefined method named "getType" of class "EasyCorp\Bundle\EasyAdminBundle\Form\Util\FormTypeHelper".

alterphp\easyadmin-extension-bundle\src\Configuration\ShortFormTypeConfigPass.php:89

**Comment by alterphp** [comment]
Did you locally modify the class ShortFormTypeConfigPass ?

Seems this is old changes from your closed PR #73.

**Comment by gonzakpo** [comment]
- https://github.com/EasyCorp/EasyAdminBundle/tree/master/src/Form/Util
- https://github.com/EasyCorp/EasyAdminBundle/tree/v1.17.14/src/Form/Util

**Comment by alterphp** [comment]
Yes, but EasyAdminExtension do not ensure compatibility with EasyAdmin master branch (that is next 2.0).

I'm surprised you've been able to install it with EasyAdmin master branch

**Comment by gonzakpo** [comment]
if clone in the vendor directly

**Comment by alterphp** [comment]
OK, but for now, EasyAdmin master branch is not supported.
