### ISSUE TITLE
EasyAdminBundle 2.0 is out! Let's update this bundle

### ISSUE THREAD

**Issue by TomasVotruba** [alterphp/EasyAdminExtensionBundle#84]
Great news :+1:  → https://github.com/EasyCorp/EasyAdminBundle/blob/master/UPGRADE-2.0.md

I would like to use EAB 2.0, but this package depends on it. **And I love this package :)**

**Comment by TomasVotruba** [comment]
@alterphp Thank you for working on this so fast :speed

**Comment by alterphp** [comment]
I lost so much time on an unrelated bug, but finally it's merged to master.

Tag is incoming !

**Comment by TomasVotruba** [comment]
Woho :tada: :clap: 

Perfect timing, I'm just working on the update and needed this just right now :)

**Comment by TomasVotruba** [comment]
FIY, I've added rector level `easy-admin-bundle20` for those who need to migrate many files.

https://github.com/rectorphp/rector/pull/871/commits/9cb3484b36910af97c292222e36ab5f57024a22b#diff-93f41fc1de597f020fa76045510b75d7
