### ISSUE TITLE
Sorting bug (extra button gets created and whole edit page gets included)

### ISSUE THREAD

**Issue by maartenvanasperen** [alterphp/EasyAdminExtensionBundle#90]
When clicking on the text from a sortable field, an extra button gets created:
![image](https://user-images.githubusercontent.com/11276046/50518856-4fc3c100-0ab8-11e9-8422-30ac7b51f723.png)

When clicking on the icon, next to the text:
![image](https://user-images.githubusercontent.com/11276046/50519014-22c3de00-0ab9-11e9-81a5-b248a7b44e0a.png)

The whole edit page gets included in the embedded list
![image](https://user-images.githubusercontent.com/11276046/50518973-f60fc680-0ab8-11e9-8373-e205fdc2e89d.png)

Versions:
alterphp/easyadmin-extension-bundle: `v2.0.1`
easycorp/easyadmin-bundle: `v2.0.2`
Symfony: `4.1`

**Comment by alterphp** [comment]
Hi @maartenvanasperen !

Do you still get this issue ?

**Comment by alterphp** [comment]
Closing as I can not reproduce the case...
