### ISSUE TITLE
Autocomplete allows creation when not found does not work

### ISSUE THREAD

**Issue by DimitriGuitton** [alterphp/EasyAdminExtensionBundle#91]
Hi,

I have a problem with one of my forms. In my form I have a field of type "easyadmin_autocomplete" as if below.

`-   property: 'questions'
                        type:     'easyadmin_autocomplete'
                        type_options: { attr: { create: true } }`

![capture d ecran du 2019-01-10 18-17-45](https://user-images.githubusercontent.com/34243266/50985216-15b8dd00-1504-11e9-87ed-caf06ff881e0.png)

The problem is that when no data is found I do not have the button to create.

Versions : 

- "alterphp/easyadmin-extension-bundle": "2.0.1"

- "easycorp/easyadmin-bundle": "^2.0",

Having found no solution after watching the docs and forums, I post my problem here.

**Comment by DimitriGuitton** [comment]
After several research, I found the problem, in my 'design.yaml', I was using my own layouut that extends EasyAdmin and not EasyAdminExtension.

**Comment by alterphp** [comment]
Ok, glad you found the fix yourself !
