### ISSUE TITLE
Form filters on date ?

### ISSUE THREAD

**Issue by pesseyjulien** [alterphp/EasyAdminExtensionBundle#95]
Hi,

Is it possible to have a form filter on a datetime field ?

Thanks,
Julien

**Comment by alterphp** [comment]
It should.

Did you try ?

**Comment by pesseyjulien** [comment]
I did, as followed : 

```
  list:
                form_filters:
                  - lastLogin
```

But it's not rendering.

**Comment by alterphp** [comment]
Yes, automatic guessing is not ready to configure datetime but you have options to do it :

Here is an example for filtering on lastLogin AFTER 

```yaml
    - { name: lastLoginAfter, property: lastLogin, operator: gte, type: datetime }
```

**Comment by pesseyjulien** [comment]
I see, thanks !

Now it display well but it does not work :/ 

for example : 

![capture d ecran 2019-01-31 a 14 50 47](https://user-images.githubusercontent.com/10850944/52058385-9d27c800-2567-11e9-8549-58a8ca21302e.jpg)

![capture d ecran 2019-01-31 a 14 50 39](https://user-images.githubusercontent.com/10850944/52058389-9f8a2200-2567-11e9-9f5a-77e5d2a84637.jpg)


Any idea what could be wrong ?

**Comment by alterphp** [comment]
Can you show me the SQL query that has been executed ?

**Comment by pesseyjulien** [comment]
Here it is : 

`SELECT DISTINCT u0_.id AS id_0, u0_.last_login AS last_login_1 FROM users u0_ LEFT JOIN user_profile u2_ ON u0_.id = u2_.user_id LEFT JOIN profile p1_ ON p1_.id = u2_.profile_id WHERE p1_.label = 'worker' AND u0_.roles LIKE '%ROLE_SUPER%' AND u0_.last_login = '2014-01-02 01:00:00' ORDER BY u0_.last_login DESC LIMIT 15;`

It puts '=' instead of '>=',  that's why !

**Comment by alterphp** [comment]
Update the bundle please, I guess you don't have the last 2.1.0 release (only 2 days old with improvements about list filters) => https://github.com/alterphp/EasyAdminExtensionBundle/releases/tag/v2.1.0

**Comment by pesseyjulien** [comment]
It does work better after the update :) 

Thanks !
