### ISSUE TITLE
label are not working

### ISSUE THREAD

**Issue by ibasaw** [alterphp/EasyAdminExtensionBundle#96]
symfony 3.4
easyadmin 1.17
extension: 1.3.3

```
            list:
                form_filters:
                    - { property: published, label: 'titi' }
                    - { property: postType, label: 'toto' }
```

but on the admin i got the property as the label, not my own label

why?

**Comment by alterphp** [comment]
I think before 2.x EasyAdmin version, you have to pass label into `type_options` array attribute

**Comment by ibasaw** [comment]
@alterphp that's it !  tahnk you.
